# Generated by Django 5.1 on 2024-08-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_alter_tablaturnos_dni_alter_tablaturnos_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaturnos',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='tablaturnos',
            name='telefono',
        ),
    ]
