# Generated by Django 5.1 on 2024-08-24 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_remove_tablaturnos_dni_remove_tablaturnos_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaturnos',
            name='turnoFecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
