# Generated by Django 5.1 on 2024-08-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_tablaturnos_turnofecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaturnos',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tablaturnos',
            name='especialidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablaturnos',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
