# Generated by Django 5.1 on 2024-08-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_alter_tablaturnos_dni_alter_tablaturnos_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaturnos',
            name='dni',
            field=models.IntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='tablaturnos',
            name='telefono',
            field=models.IntegerField(null='true'),
        ),
    ]
