# Generated by Django 5.1 on 2024-08-28 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_remove_tablaturnos_turnofecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaturnos',
            name='turnoFecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
